# **Task 1**

Your goal is to find the answer of the dot product of the matrices of sizes (2,3), (3,5), (5,2) and (3,3).

## **Workflow:**
1. Define the matrices of given sizes.
2. Print the matrices.
3. Use the np.dot function.
4. Print the output at each step.
5. Print the result.

(Print the shape of matrix always with the matrix)


In [3]:
# Import Numpy
import numpy as np

In [ ]:
# Define the 4 matrices as A,B,C,D
A=np.random.randint(1,10,(2,3))
B=np.random.randint(1,10,(3,5))
C=np.random.randint(1,10,(5,2))
D=np.random.randint(1,10,(2,3))


In [ ]:
# Print the 4 matrices
print(A)
print(B)
print(C)
print(D)


[[5 1 5]
 [6 5 3]]
[[8 1 7 9 4]
 [1 7 1 1 9]
 [3 1 5 8 9]]
[[2 1]
 [7 8]
 [6 9]
 [3 1]
 [9 2]]
[[2 6 6]
 [5 8 1]]


In [ ]:
# Find the Dot Product of matrices
result=np.dot(np.dot(np.dot(A,B),C),D)
print(result)


[[ 7917 16926 10101]
 [10069 21478 12749]]


# ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

Now the task is to define a function named is_compatible() that takes 2 matrices as input and only allows the dot product if the condition number of **columns** in the first matrix (A) matches the number of **rows** in the second matrix (B).

Print the ouput if condition is satisfied
Else print "Dimension Error!!"




In [ ]:
def is_compatible(A, B):
  rowA,colA=A.shape
  rowB,colB=B.shape
  if (colA==rowB):
    print(np.dot(A,B))
  else:
    print("Dimension Error!!")

In [ ]:
# Find Dot product only if the matrices are compatible
A=np.random.randint(1,10,(2,3))
B=np.random.randint(1,10,(2,3))
is_compatible(A,B)


Dimension Error!!


# **Task 2**

Your goal is to define a function that simulates a number-guessing game called "Up-Down." The function, named up_down, should take an integer rounds as input, representing the number of turns the player gets.

Game Rules:

1. The player inputs a number between 1 and 12 for each round.
2. The computer randomly selects a number between 1 and 12.
3. The scoring system is as follows:
  
  a. If computer's guess is less than 7 and the player gains points equivalent to their guess if their guess is also less than 7, otherwise, they lose points equivalent to their guess.
  
  b. If computer's guess is exactly 7, the player gains 14 points if thier guess is 7, otherwise, they lose points equivalent to their guess.
  
  c. If computer's guess is greater than 7 and the player gains points equivalent to their guess if their guess is also greater than 7, otherwise, they lose points equivalent to their guess.

4. The game continues until:

  a. The player reaches more than 30 points, they win.

  b. The player reaches less than -30 points, they lose.

  c. The maximum number of rounds is reached.
  
At the end of the game, the function should print the final score.

Your task is to implement this function in Python using the given rules.

In [7]:
def up_down(rounds):
  score=0
  while(rounds>0):
    human_guess=int(input("Enter ur guess:- "))
    computer_guess=np.random.randint(1,13)
    if(computer_guess<7):
      if(human_guess<7):
        score+=human_guess
      else:
        score-=human_guess
    elif(computer_guess==7):
      if(human_guess==7):
        score+=14
      else:
        score-=14
    else:
      if(human_guess>7):
        score+=human_guess
      else:
        score-=human_guess
    if(score>30):
      print("You Won!!")
      break
    elif(score<-30):
      print("You Lost!!")
      break
    rounds-=1
  print("Final score is: ",score)
x=int(input("Enter number of rounds: "))
up_down(x)


Enter number of rounds: 3
Enter ur guess:- 2
Enter ur guess:- 5
Enter ur guess:- 12
Final score is:  19
